### ISSUE TITLE
Andromeda crash with user-defined modifications

### ISSUE THREAD

**Issue by LasseLorentzen** [compomics/searchgui#116]
Hi,

I have trouble with Andromeda crashing when including 2 user-defined modifications in my search (Nitration of Y + Nitration of W).  Andromeda runs without problems without these modifications included.

I've attached a screenshot of the error message. I hope you can help with this. 

Cheers, 
Lasse

![image](https://cloud.githubusercontent.com/assets/21430519/18158066/0adb632e-7021-11e6-9016-522c82118ea6.png)

**Comment by hbarsnes** [comment]
Hi Lasse,

It was a bug on our end where we for some reason did not add the user PTMs to Andromeda's list of available PTMs. Here's a beta version that ought to solve the problem: https://www.dropbox.com/s/39t88e76bwz7bx0/SearchGUI-3.1.1-beta-windows.zip?dl=0

We'll release a new proper version as soon as possible.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Lasse,

We've just released SearchGUI v3.1.1 which should allow you to use your user-defined PTMs with Andromeda. If this is not the case, please let us know and we'll reopen the issue.

Best regards,
Harald

**Comment by LasseLorentzen** [comment]
Hi Harald,

The 3.1.1 version runs without any problems. Thank you for the help and the swift response. 

Cheers, 
Lasse

**Comment by LasseLorentzen** [comment]
Hi again Harald,

It seems I still have issues with Andromeda and user-defined PTMs. Although Andromeda now runs without errors (as stated above), there's no identifications of these PTMs from Andromeda run from searchGUI alone.  I do get the expected identification of the PTMs some of the other algorithms (comet, msamanda etc), and also when running andromeda thorugh the MaxQuant interface (albeit with slightly modified parameters).

I'm sorry to bring this up again, but I only just had the time to actually go into the search results from the new searchGUI version. I hope you can help me figure out what went wrong this time. 

Kind regards,
Lasse

**Comment by hbarsnes** [comment]
Hi Lasse,

That is strange. Can you give me access to your SearchGUI output (plus mgf and FASTA file) so that I can try to reproduce the issue on my side?

Best regards,
Harald

**Comment by LasseLorentzen** [comment]
Hi Harald, 

Sorry for the long response time, but I've been hung up with lab stuff. I've uploaded the .mgf I've tested, the .fasta (smaller database for testing purposes) as well as searchGUI/PeptideShaker output files from searches run with either Andromeda or MS Amanda alone. https://www.dropbox.com/s/yrcomsf4msiaack/SearchGUI_test.zip?dl=0

Please let me know if you need other files or more information from my side.

Thank you for the help

**Comment by hbarsnes** [comment]
Hi Lasse,

Thanks for the files. I can confirm that I don't see any nitration in the main tables when loading the Andromeda results on my side either. However  I do see them in the Spectrum IDs tab, but all of them are scoring very poorly.

Here's one example from Andromeda alone >

![andromeda alone](https://cloud.githubusercontent.com/assets/13151214/19152337/d988879e-8bd1-11e6-8ec8-eb352c6cb1fc.png)

Note that is _does_ find peptides with nitration, but none of them score high enough to be selected.

Peptides with nitration from Andromeda can also be seen when loading both the Andromeda and MS Amanda together >

![andromeda and ms amanda](https://cloud.githubusercontent.com/assets/13151214/19152388/0ce34aca-8bd2-11e6-96dc-d46c2f6fab63.png)

But again the Andromeda results score very badly compared to MS Amanda. One could question the quality of the PSM selected by MS Amanda though, as there are lots of high peaks not annotated. So perhaps Andromeda is doing the right thing in not giving it a high score?

However, in order to figure out why Andromeda does not score any peptides with nitration high enough to be maintained I think you have to contact the Andromeda developers. As there is not a lot we can do with this on our side I'm afraid.

Given that this problem no longer seems to be related to the use of user modifications in Andromeda (Andromeda is not even able to tell default and user modification apart as they are all in the same input xml file anyway), I will now close this issue. But please feel free to open a new one if you manage to figure out why Andromeda handles the nitrations so differently from the other search engines you've tried?

In the mean time I would simply suggest not using Andromeda for this particular dataset? Which is partly why we support multiple search engines in SearchGUI in the first place. :)

Best regards,
Harald

**Comment by LasseLorentzen** [comment]
Thank you for the feed back. I think I will just leave the issue and skip the andromeda engine for this purpose - it does not come with a lot of unique PSMs anyway when including more search engines.

Thank you very much for the help.

Cheers,
Lasse

**Comment by hbarsnes** [comment]
Hi Lasse,

No worries. And in any case we managed to fix some bugs with user modifications and Andromeda along the way. :)

Best regards,
Harald
